[TypeScript][Skill] Implement TypeScript 4
southworks/botframework-solutions pull request #437
Opened 2020-09-04 18:12 UTC by FedericoBernal

### Purpose
*What is the context of this pull request? Why is it being done?*

A new version of TypeScript has been released (v4)

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

- Updated TypeScript version to `4.0.2` on the sample
- Updated TypeScript version to `4.0.2` on the template

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

### Checklist

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

2020-09-09 18:59 UTC, matiasroldan6 commented on templates/typescript/samples/sample-skill/src/bots/defaultActivityHandler.ts
> +    // eslint-disable-next-line @typescript-eslint/no-unused-vars
why is this needed now?

2020-09-09 18:59 UTC, matiasroldan6 commented on templates/typescript/samples/sample-skill/src/extensions/turnContextEx.ts
> +// eslint-disable-next-line @typescript-eslint/no-namespace
why is this needed now?

2020-09-09 19:00 UTC, matiasroldan6 commented on templates/typescript/samples/sample-skill/src/index.ts
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars
same as above :)

2020-11-20 14:23 UTC, Batta32 requested changes
@matiasroldan6 check my feedback, also don't we have any warning to fix here with the bump of the eslint version?

2020-11-20 14:23 UTC, Batta32 commented on templates/typescript/samples/sample-skill/.eslintrc.json
> +        "@typescript-eslint/consistent-type-assertions": 1,
Following parity with #472 
```suggestion
        "@typescript-eslint/consistent-type-assertions": ["error", { "assertionStyle": "as" }],
```

2020-11-20 14:47 UTC, matiasroldan6 commented on templates/typescript/samples/sample-skill/.eslintrc.json
> +        "@typescript-eslint/consistent-type-assertions": 1,
I checked and no new eslint issues appeared with the version bump, but will doublecheck

2020-11-20 14:49 UTC, matiasroldan6 commented
@Batta32 I checked and no new eslint issues appeared with the version bump, but will doublecheck

2020-11-20 17:35 UTC, Batta32 approved these changes
LGTM

2021-06-02 18:04 UTC, closed without merging