[Documentation] Update references to main branch
southworks/botframework-solutions pull request #443
Opened 2020-09-14 18:49 UTC by fran893

### Purpose
*What is the context of this pull request? Why is it being done?*

As the **master** will be renamed to **main**, we updated all the references to this branch. 

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

We modified the following files:

- Java files
- Markdown files
- YAML files
- JSON files
- XML files
- JavaScript files
- CSS file
- PowerShell file
- Gitignore file
- HTML+Razor file

Furthermore, we updated the references to external repositories and fixed broken links.

### Tests
*Is this covered by existing tests or new ones? If no, why not?*
*-*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*
*-*

### Checklist
*-*

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [x] I have updated related documentation

2020-09-21 18:02 UTC, Batta32 requested changes
@fran893 @FedericoBernal FYI, review the requested changes, but I'll apply the fix, this is just FYI

2020-09-22 17:03 UTC, Batta32 requested changes

2020-09-22 17:08 UTC, Batta32 approved these changes
LGTM

2020-09-22 17:16 UTC, FedericoBernal commented on docs/_docs/overview/virtual-assistant-template.md
> -### Escalate Dialog
Why have we deleted this?

2020-09-22 17:16 UTC, FedericoBernal commented on docs/_docs/overview/virtual-assistant-template.md
> -### Event processing
Same as before

2020-09-22 17:21 UTC, Batta32 commented on docs/_docs/overview/virtual-assistant-template.md
> -### Escalate Dialog
The `EscalateDialog` doesn't exist in the Virtual Assistant, that's why I deleted it

2020-09-22 17:21 UTC, Batta32 commented on docs/_docs/overview/virtual-assistant-template.md
> -### Event processing
Same, the handle of `OnEventAsync` method was deleted in the VA

2020-09-22 17:24 UTC, FedericoBernal approved these changes
LGTM!

2021-06-02 17:58 UTC, closed without merging