[C#][VSIX] Add unit tests for VSIX project
southworks/botframework-solutions pull request #461
Opened 2020-10-20 20:58 UTC by fran893

### Purpose
*What is the context of this pull request? Why is it being done?*

The VSIX project does not have unit tests. 

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

We added unit tests in the VSIX Project in order to cover all the replacement of placeholders

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

_The unit tests for the Virtual Assistant and Skill templates_

![image](https://user-images.githubusercontent.com/51216149/96643190-99b90f00-12fd-11eb-9265-7b1781aa920d.png)

_The folders that are going to be created_

![image](https://user-images.githubusercontent.com/51216149/96643061-68d8da00-12fd-11eb-8a56-75ccb832e6bc.png)

_Files which are going to be created, specifying if the placeholder will be replaced or not_

![image](https://user-images.githubusercontent.com/51216149/96643148-8b6af300-12fd-11eb-8df6-fd0893b323bb.png)

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

### Checklist

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

2020-10-20 21:05 UTC, Batta32 requested changes
1. Following folder structure of other solutions e.g VA/Skill/Bot-solutions, you need to replace `BotTemplateVSIX.Test` to `BotTemplateVSIX.Tests`
1. Also, I think that it would be better to rename `BotTemplateVSIX` to just `VSIX`
1. I'm not quite sure about the result of these tests. You are just validating which are the files that contains or not placeholders. I'm meaning that you are not asserting things, you are just listing. To understand this, compare the execution of these tests with the TS generator tests. Compare both

2020-10-22 17:33 UTC, Batta32 requested changes
The name of the `[TestMethod]` should be boolean: Example:
```csharp
[TestMethod]
public void Test_Folder_Length_Are_Equal
```

2020-10-22 17:33 UTC, Batta32 commented on templates/csharp/Templates.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "BotTemplatesVSIX.Test", "BotTemplatesVSIX.Test\BotTemplatesVSIX.Test.csproj", "{029BC218-905F-4D2D-9DF6-0F0636744B18}"
This is deprecated, right?

2020-10-22 17:33 UTC, Batta32 commented on templates/csharp/VSIX.Tests/GeneratorVirtualAssistantTests.cs
> +        };
The brakets `{ }` are not aligned between lists

2020-10-22 17:33 UTC, Batta32 commented on templates/csharp/VSIX.Tests/GeneratorVirtualAssistantTests.cs
> +            XmlNodeList foldersList = templateFile.GetElementsByTagName("Folder");
I see this logic repeated in each `[TestMethod]`, can we abstract this as a private property or maybe as `[TestInititialize]`. See [this](https://github.com/microsoft/botframework-solutions/blob/master/templates/csharp/VA/VA.Tests/BotTestBase.cs#L54).

2020-10-23 12:52 UTC, VictorGrycuk commented on templates/csharp/VSIX.Tests/GeneratorVirtualAssistantTests.cs
> +                string path = Path.Combine("..\\..\\..\\..\\VA\\VA\\", folder.Attributes["TargetFolderName"].Value);
Would it be possible for the `file` to not thave the `"TargetFileName"` property?

2020-10-23 12:54 UTC, Batta32 requested changes
Comment each tests as MS [does](https://github.com/microsoft/botframework-solutions/blob/master/templates/csharp/VA/VA.Tests/MainDialogTests.cs#L57)

2020-10-23 12:54 UTC, Batta32 commented on templates/csharp/VSIX.Tests/GeneratorVirtualAssistantTests.cs
> +        private readonly string _vaProjectTemplatePath = @"..\..\..\..\VA\VA\VAProjectTemplate.vstemplate";
The idea to use [Path.Combine](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.combine?view=netcore-3.1) is to avoid to use `\` in a string.

This should be changes to:
``` csharp
private readonly string _vaProjectTemplatePath = Path.Combine("..", "..", "..", "..", "VA", "VA", "VAProjectTemplate.vstemplate");
```

2020-10-23 12:54 UTC, Batta32 commented on templates/csharp/VSIX.Tests/GeneratorVirtualAssistantTests.cs
> +                string path = Path.Combine("..\\..\\..\\..\\VA\\VA\\", folder.Attributes["TargetFolderName"].Value);
The idea to use [Path.Combine](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.combine?view=netcore-3.1) is to avoid to use `\` in a string.

`Path.Combine` receives an array of strings

2020-10-23 15:26 UTC, fran893 commented on templates/csharp/VSIX.Tests/GeneratorVirtualAssistantTests.cs
> +                string path = Path.Combine("..\\..\\..\\..\\VA\\VA\\", folder.Attributes["TargetFolderName"].Value);
For what I saw in the _.vstemplate_ file, all the files have the `"TargetFileName"` property, in the case of folders, the have the `"TargetFolderName"` property

2020-10-26 18:23 UTC, Batta32 commented
Be careful, this should be pointing to `next`, `master`/`main` is for bugfixes

2021-06-02 22:17 UTC, closed without merging