[Functional Tests] Update yaml files with latest changes
southworks/botframework-solutions pull request #491
Opened 2020-12-16 19:48 UTC by fran893

### Purpose
*What is the context of this pull request? Why is it being done?*
Added changes from PR 3602

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

### Checklist

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

2020-12-17 12:47 UTC, Batta32 requested changes
I recommend you to check all the execution with the [C# VA](https://github.com/southworks/botframework-solutions/blob/feature/southworks/functional-test/ts-yamls-stages/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.FunctionalTests/Nightly-Dotnet-VirtualAssistantToSkill.yml).

I haven't finished to review the PR, but I found a lot of disparities with the C# VA.

2020-12-17 12:47 UTC, Batta32 commented on templates/typescript/samples/sample-assistant/functional-tests/sample-assistant.yml
> -    failOnStderr: true
Following [C# VA YML](https://github.com/southworks/botframework-solutions/blob/feature/southworks/functional-test/ts-yamls-stages/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.FunctionalTests/Nightly-Dotnet-VirtualAssistantToSkill.yml) this is not removed and it's included in the VA's Job not in the Skill's job as you are adding here.

2020-12-17 12:47 UTC, Batta32 commented on templates/typescript/samples/sample-assistant/functional-tests/sample-assistant.yml
> -    enabled: false
Same as before, and be careful of the `displayName` this should be: `Build: VA - Build project` or `Build: VA - Run npm build`

2020-12-17 12:47 UTC, Batta32 commented on templates/typescript/samples/sample-assistant/functional-tests/sample-assistant.yml
> -
Same as before

2020-12-17 12:47 UTC, Batta32 commented on templates/typescript/samples/sample-assistant/functional-tests/sample-assistant.yml
> +    failOnStderr: true
Following the comments of the VA's job, this is not correct

2020-12-17 12:47 UTC, Batta32 commented on templates/typescript/samples/sample-assistant/functional-tests/sample-assistant.yml
> +      workingDirectory: 'templates/typescript/samples/functionalTests/$(VirtualAssistantBotName)'
This is not correct, as this logic in the [setDirectLineSteps.yml](https://github.com/southworks/botframework-solutions/blob/feature/southworks/functional-test/ts-yamls-stages/yaml/setDirectLineSteps.yml).

2020-12-18 14:16 UTC, Batta32 requested changes
I reviewed the Nightly-Dotnet-VirtualAssistantToSkill.yml vs README.md of that C# VA. But this should be applied in all the documents/ymls

- [X] (1) In all documentation, remove [luis-apis](https://github.com/southworks/botframework-solutions/pull/491/files#diff-b453bec10bfa20af38fe52b4283424d4274ee5e0d4cbe84123d0c2a54e63c378R5) as it's not used, also in the ymls
- [ ] (2) Is it needed `BuildPlatform`? I didn't see any `yml` using that variable
- [ ] (3) Is it needed `ServicePrincipal`? I didn't see any `yml` using that variable
- [ ] (4) Is it needed `Azure_Tenant`? I didn't see any `yml` using that variable
- [ ] (5) Is it needed `AzureDevOps-ServicePrincipal-Secret`? I didn't see any `yml` using that variable
- [ ] (6) Is it needed `privacyUrl`? I didn't see any `yml` using that variable
- [X] (7) Can we unify the nomenclature of the templates ymls? See the suffix step
- [X] (8) Can we abstract the `Use Nuget 4.9.1` step to another yml?
- [ ] (9) The yml `npmInstallRequirements` install yeoman, but in C# this is not needed, is this correct?
- [X] (10) In the documentation and in the `dotnetBuildSteps` I see "Dotnet Build" and "Dotnet Test" as display name that doesn't follow the nomenclature of the ymls
- [X] (11) In the documentation and in the `deploySteps` I see "Deploy" as display name that doesn't follow the nomenclature of the ymls

2020-12-18 17:41 UTC, Batta32 requested changes
Minor changes:
- [X] (1) Order variables (yml/readme) alphabetically
- [X] (2) VA's Readmes The VA's - Skill dependency after the Skill should be after the VA's job
- [X] (3) C# VA's readme contains the installation of yeoman, we need to remove this
- [X] (4) TS VA's readme "Use of generator-bot-virtualassistant & generator-bot-virtualassistant:skill", we can remove the `& generator-bot-virtualassistant:skill` part
- [X] (5) The note: _> **Note**: system.debug, BuildPlatform and BuildConfiguration variables should be configured checking the "Let users override this value when running this pipeline" option._ Is not present in all the readmes, is this okay?
- [X] (6) Use Note instead of NOTE (or remove the `Note` text maybe to avoid this issues)
- [X] (7) C# Skill Readme mentions SkillSample.yml instead of the Nightly one
- [X] (8) Check the steps of the TS/C# Skill Readme (names and order)
- [ ] ~(9) TS VA's uses `remotemanifest` for connect command, I think that this is not correct, right @matiasroldan6 ?~
- [X] (10) TS Skill Readme mentions `SkillSample.yml` instead of the Nightly one

2020-12-18 17:41 UTC, Batta32 commented on templates/typescript/samples/sample-skill/functional-tests/README.md
> +|      | BotBuilderPackageVersion | Version of the BotBuilder package|
```suggestion
|      | BotBuilderPackageVersion | Version of the BotBuilder package |
```

2020-12-18 18:01 UTC, matiasroldan6 commented on samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.FunctionalTests/Nightly-Dotnet-VirtualAssistantToSkill.yml
> +  # BotLanguage: The supported language of your bot
maybe we could call this `BotLanguages: The supported languages of your bot`. Since it can be more than one, plus we are equalling it to a variable named BotLanguages below

2020-12-18 19:51 UTC, Batta32 approved these changes
LGTM

2020-12-18 19:52 UTC, matiasroldan6 approved these changes

2020-12-18 19:52 UTC, merged