[Documentation] Update Functional Test documents to follow SDK approach
southworks/botframework-solutions pull request #492
Opened 2020-12-22 14:54 UTC by Batta32

### Purpose
*What is the context of this pull request? Why is it being done?*

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

### Checklist

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

2020-12-22 15:49 UTC, VictorGrycuk approved these changes
LGTM

2020-12-23 13:07 UTC, fran893 requested changes

2020-12-23 13:07 UTC, fran893 commented on samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.FunctionalTests/README.md
> +This sections described the testing scenarios for Virtual Assistants, for each one of them we provide a high level goal description of the primary test case.
This -> These

2020-12-23 13:07 UTC, fran893 commented on samples/csharp/skill/SkillSample.FunctionalTests/README.md
> +This sections described the testing scenarios for Skills, for each one of them we provide a high level goal description of the primary test case.
This -> These

2020-12-23 13:07 UTC, fran893 commented on templates/typescript/samples/sample-assistant/functional-tests/README.md
> +This sections described the testing scenarios for Virtual Assistants, for each one of them we provide a high level goal description of the primary test case.
This -> These

2020-12-23 13:07 UTC, fran893 commented on templates/typescript/samples/sample-skill/functional-tests/README.md
> +This sections described the testing scenarios for Skills, for each one of them we provide a high level goal description of the primary test case.
This -> These

2020-12-23 14:59 UTC, matiasroldan6 approved these changes

2020-12-23 15:00 UTC, merged