[Bot-Solutions] [TypeScript] Fix MultiProviderAuthDialog localization
southworks/botframework-solutions pull request #495
Opened 2021-02-02 18:44 UTC by VictorGrycuk

### Purpose
*What is the context of this pull request? Why is it being done?*

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

### Checklist

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

2021-02-04 13:05 UTC, Batta32 approved these changes
All the changes LGTM!!

2021-02-05 13:58 UTC, fran893 requested changes

2021-02-05 13:58 UTC, fran893 commented on sdk/typescript/libraries/bot-solutions/src/authentication/multiProviderAuthDialog.ts
> +    private getLocalizedDialog(locale: string, connectionName: string, settings: OAuthPromptSettings) {
I don't remember about TS, but here, don't we need to add the return type in the method signature?

2021-02-05 14:00 UTC, Batta32 commented on sdk/typescript/libraries/bot-solutions/src/authentication/multiProviderAuthDialog.ts
> +    private getLocalizedDialog(locale: string, connectionName: string, settings: OAuthPromptSettings) {
+1, @VictorGrycuk have you tested the linter/build/tests?

2021-02-05 14:34 UTC, matiasroldan6 commented on sdk/typescript/libraries/bot-solutions/src/authentication/multiProviderAuthDialog.ts
> +            this.addDialog(new WaterfallDialog(DialogIds.authPrompt, authSteps));
I think we already have this change somewhere else, in 1.0/next? But it's ok

2021-02-05 14:40 UTC, VictorGrycuk commented on sdk/typescript/libraries/bot-solutions/src/authentication/multiProviderAuthDialog.ts
> +            this.addDialog(new WaterfallDialog(DialogIds.authPrompt, authSteps));
Several changes are already in next, but we need this in master as it is a bugfix

2021-02-05 17:42 UTC, VictorGrycuk commented on sdk/typescript/libraries/bot-solutions/src/authentication/multiProviderAuthDialog.ts
> +    private getLocalizedDialog(locale: string, connectionName: string, settings: OAuthPromptSettings) {
Feedback applied!

2021-02-05 17:43 UTC, Batta32 commented on sdk/typescript/libraries/bot-solutions/src/authentication/multiProviderAuthDialog.ts
> +    private getLocalizedDialog(locale: string, connectionName: string, settings: OAuthPromptSettings) {
LGTM

2021-06-02 22:15 UTC, merged